# Generated by Django 4.0 on 2021-12-24 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.FileField(upload_to='media/')),
                ('maqola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.maqola')),
            ],
        ),
    ]
